version: 2

before:
  hooks:
    - go generate -v ./...

builds:
  - id: dazzle
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/khulnasoft/dazzle/cmd/core.version={{.Version}}-{{.ShortCommit}}
    goos:
      - darwin
      - linux

  - id: dazzle-util
    env:
      - CGO_ENABLED=0
    main: main-util.go
    binary: dazzle-util
    flags:
      - -tags=util
    ldflags:
      - -s -w -X github.com/khulnasoft/dazzle/cmd/util.version={{.Version}}-{{.ShortCommit}}
    goos:
      - darwin
      - linux

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.tar.gz"
    files:
      - dist/**  # Adjust based on your output files

# Removed snapshot_name; GoReleaser uses default snapshot behavior now
snapshot: {}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto

dockers:
  - goos: linux
    goarch: amd64
    goarm: ""
    dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/khulnasoft/dazzle:{{ .Tag }}"
    extra_files:
      - README.md
