version: 2

before:
  hooks:
    - go generate -v ./...
builds:
- id: dazzle
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/khulnasoft/dazzle/cmd/core.version={{.Version}}-{{.ShortCommit}}
  goos:
  - darwin
  - linux
- id: dazzle-util
  env:
  - CGO_ENABLED=0
  main: main-util.go
  binary: dazzle-util
  flags:
    - -tags=util
  ldflags:
  - -s -w -X github.com/khulnasoft/dazzle/cmd/util.version={{.Version}}-{{.ShortCommit}}
  goos:
  - darwin
  - linux
archives:
- id: dazzle
  builds:
  - dazzle
  format: tar.gz
  format_overrides:
    - goos: darwin
      format: zip
    - goos: linux
      format: tar.gz
- id: dazzle-util
  files:
  - "none*"
  format: binary
  builds:
  - dazzle-util
  format_overrides:
    - goos: darwin
      format: zip
    - goos: linux
      format: tar.gz
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  prerelease: auto
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    dockerfile: Dockerfile
    image_templates:
    - "ghcr.io/khulnasoft/dazzle:{{ .Tag }}"
    extra_files:
    - README.md
